openapi: 3.0.1
info:
  title: '@jupiterone/security-policy-builder'
  description: >-
    Configurable compilation of policies, standards, and procedures
    documentation.
  x-cortex-git:
    github:
      repository: JupiterOne/security-policy-builder
  x-cortex-owners:
    - type: group
      name: JupiterOne/Apps
  x-cortex-tag: '@jupiterone/security-policy-builder'
  x-cortex-service-groups:
    - tier-4
